# Verify that the IP address fields are not null and that there are unique entries in the top 10 list.

version: 2

models:
  - name: top_10_users_by_clicks
    columns:
      - name: ip
        tests:
          - not_null
          - unique
