
version: 2
# Verify that the errors field does not contain null values.
models:
  - name: errors_404_hourly
    columns:
      - name: errors
        tests:
          - not_null
# Verify that the errors field does not contain null values.
  - name: errors_non_404_hourly
    columns:
      - name: errors
        tests:
          - not_null
# Verify that the calculated percentage value is between 100% and 0%, inclusive.
  - name: percentage_requests_errors_404
    columns:
      - name: percentage_404_errors
        tests:
          - dbt_utils.expression_is_true:
              expression: ">=0"
          - dbt_utils.expression_is_true:
              expression: "<=100"
# Verify that the calculated percentage value is between 100% and 0%, inclusive.
  - name: percentage_requests_errors_non_404
    columns:
      - name: percentage_non_404_errors
        tests:
          - dbt_utils.expression_is_true:
              expression: ">=0"
          - dbt_utils.expression_is_true:
              expression: "<=100"
